const types = {
  CHANGE_AUTH_STATUS: 'CHANGE_AUTH_STATUS',
  CHANGE_DARK_MODE: 'CHANGE_DARK_MODE',
  CHANGE_ISDATA_CHANGED: 'CHANGE_ISDATA_CHANGED',
  CHANGE_RECENT_SEARCH: 'CHANGE_RECENT_SEARCH',
  CHANGE_USER_DATA: 'CHANGE_USER_DATA',
  RESET_MESSAGES: 'RESET_MESSAGES',
};

export default types;
