export const weatherImagesObj = {
  '01d': require('../assets/images/weather/01d.png'),
  '02d': require('../assets/images/weather/02d.png'),
  '03d': require('../assets/images/weather/03d.png'),
  '04d': require('../assets/images/weather/04d.png'),
  '09d': require('../assets/images/weather/09d.png'),
  '10d': require('../assets/images/weather/10d.png'),
  '11d': require('../assets/images/weather/11d.png'),
  '13d': require('../assets/images/weather/13d.png'),
  '01n': require('../assets/images/weather/01n.png'),
  '02n': require('../assets/images/weather/02n.png'),
  '03n': require('../assets/images/weather/03n.png'),
  '04n': require('../assets/images/weather/04n.png'),
  '09n': require('../assets/images/weather/09n.png'),
  '10n': require('../assets/images/weather/10n.png'),
  '11n': require('../assets/images/weather/11n.png'),
  '13n': require('../assets/images/weather/13n.png'),
  '50n': require('../assets/images/weather/50n.png'),
};
